apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
data:
  username: dmlnbmFuCg==
  password: YWJjMTIzCg==

---
apiVersion: v1  
kind: Pod
metadata:
  name: secret-pod
spec: 
  containers:
  - name: nginx
    image: nginx
    envFrom:
      - secretRef:
          name: secret-basic-auth
        
  